#################################################
# Global
#################################################

.set-max-jobs: &set-max-jobs
  - |
    case "$CMAKE_GENERATOR" in
      'Unix Makefiles')
        export CMAKE_BUILD_PARALLEL_LEVEL=$MAKEFILE_JOBS ;;
      'Ninja')
        export CMAKE_BUILD_PARALLEL_LEVEL=$NINJA_JOBS ;;
      *)
        export CMAKE_BUILD_PARALLEL_LEVEL=1 ;;
    esac
    echo "CMAKE_BUILD_PARALLEL_LEVEL='$CMAKE_BUILD_PARALLEL_LEVEL'"

.add-deploy-keys: &add-deploy-keys
  - |
    ##
    ## If SSH keys are defined then start ssh-agent and add the keys
    ##
    if ! [ -z ${DEPLOY_USER_KEY+x} ] && ! [ -z ${DEPLOY_SERVER_HOST_KEYS+x} ]; then eval $(ssh-agent -s); fi
    if ! [ -z ${DEPLOY_USER_KEY+x} ]; then echo "$DEPLOY_USER_KEY" | tr -d '\r' | ssh-add - > /dev/null; fi
    if ! [ -z ${DEPLOY_SERVER_HOST_KEYS+x} ]; then mkdir -p ~/.ssh && chmod 700 ~/.ssh; fi
    if ! [ -z ${DEPLOY_SERVER_HOST_KEYS+x} ]; then echo "$DEPLOY_SERVER_HOST_KEYS" >> ~/.ssh/known_hosts; fi

.enable-gcc-toolset: &enable-gcc-toolset
  - |
    if [[ -f /opt/rh/gcc-toolset-15/enable ]]; then
      source /opt/rh/gcc-toolset-15/enable
    elif [[ -f /opt/rh/gcc-toolset-14/enable ]]; then
      source /opt/rh/gcc-toolset-14/enable
    else
      echo "No GCC Toolset found"
    fi

.linux-enable-gcc-toolset:
  before_script:
    - *enable-gcc-toolset

.linux-ccache:
  cache:
    key: $CI_JOB_NAME
    paths:
      - ccache/
  before_script:
    - !reference [ ".todo_before_script", "before_script" ]
    - *enable-gcc-toolset
    - mkdir -p ccache
    - echo "max_size = $CCACHE_SIZE" > ccache/ccache.conf
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache
    - ccache -s
  after_script:
    - export CCACHE_DIR=${PWD}/ccache
    - ccache -s


.job-linux-build:
  stage: build 🏗
  tags: [ "docker-flat" ]
  extends: .linux-ccache
  script:
    - *set-max-jobs
    - mkdir work && cd work
    - echo "cmake -G "$CMAKE_GENERATOR" $DEFAULT_CMAKE_OPTIONS -DCMAKE_INSTALL_PREFIX="$PWD/../OUTPUT" $CMAKE_OPTIONS .."
    - cmake -G "$CMAKE_GENERATOR" $DEFAULT_CMAKE_OPTIONS -DCMAKE_INSTALL_PREFIX="$PWD/../OUTPUT" $CMAKE_OPTIONS ..
    - cmake --build .

# Files required by the flexisip_tester bin
.tester-artifacts:
  artifacts:
    paths:
      - work/bin/flexisip_conference_tester
      - work/lib{,64}/
      - "**grammar"
      - tester/cert
      - tester/config
      - tester/images
      - tester/scripts
      - tester/sounds

#################################################
# RPM
#################################################

.job-linux-rpm:
  stage: package 📦
  tags: [ "docker-flat" ]
  extends:
    - .rules-default  # ⚠ See `rules.yml`
  variables:
    CMAKE_GENERATOR: 'Ninja'
  script:
    - *enable-gcc-toolset
    - *set-max-jobs
    - mkdir build && cd build
    - cmake -G $CMAKE_GENERATOR $DEFAULT_PACKAGING_CMAKE_OPTIONS $CMAKE_OPTIONS -DCPACK_GENERATOR=RPM ..
    - cmake --build . --target package
  artifacts:
    paths:
      - build/*.rpm
    when: always
    expire_in: 1 week

#################################################
# DEB
#################################################

.job-linux-deb:
  stage: package 📦
  tags: [ "docker-flat" ]
  extends:
    - .rules-default  # ⚠ See `rules.yml`
  variables:
    CMAKE_GENERATOR: 'Ninja'
  script:
    - *set-max-jobs
    - mkdir build && cd build
    - cmake -G $CMAKE_GENERATOR $DEFAULT_PACKAGING_CMAKE_OPTIONS $CMAKE_OPTIONS -DCPACK_GENERATOR=DEB ..
    - cmake --build . --target package
  artifacts:
    paths:
      - build/*.deb
      - build/*.ddeb
    when: always
    expire_in: 1 week

#################################################
# DEPLOY
#################################################

.job-deploy:
  stage: deploy 🚀
  tags: [ "docker-deploy-flat" ]
  extends: .rules-deploy  # ⚠ See `rules.yml`
  variables:
    # Do not clone, only use artifacts (TODO 'none' doesn't clean, we are using 'fetch' until we find a way)
    GIT_STRATEGY: fetch
    # Aim for a specific commit to avoid unintentional changes since the script is shared with other projects
    DEPLOY_SCRIPT: 'wget -qO- --header="PRIVATE-TOKEN: ${TOOLS_REPOSITORY_TOKEN}" https://gitlab.linphone.org/api/v4/projects/368/repository/files/deploy_packages.sh/raw?ref=58a7c34c'
  before_script:
    - *add-deploy-keys
  script: 'bash <(eval ${DEPLOY_SCRIPT}) ${DISTRIB} ${RELEASE}'

#################################################
# Nightly only
#################################################

.job-linux-build-nightly:
  extends:
    - .job-linux-build
    - .rules-nightly  # ⚠ See `rules.yml`

#################################################
# Build Makefile
#################################################

.job-makefile-gcc:
  extends: .job-linux-build-nightly
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++


.job-makefile-clang:
  extends: .job-linux-build-nightly
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++

#################################################
# Build Ninja
#################################################

.job-ninja-gcc:
  extends:
    - .job-linux-build
    - .rules-manual  # ⚠ See `rules.yml`
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++


.job-ninja-clang:
  extends:
    - .job-linux-build
    - .rules-dev  # ⚠ See `rules.yml`
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++

#################################################
# Tests
#################################################

.unit-test:
  stage: test 🧪
  tags: [ "docker-test-flexisip-flat" ]
  extends: .rules-dev  # ⚠ See `rules.yml`
  variables:
    # Do not clone, only use artifacts (TODO 'none' doesn't clean, we are using 'fetch' until we find a way)
    GIT_STRATEGY: fetch
    LSAN_SUPPRESSIONS_FILE_PATH: "./sanitizer_ignore.txt"
    LOG_FILE_PATTERN: flexisip_unit_tests
    LOGS_DIR: ${CI_PROJECT_DIR}/logs
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib
    - export LSAN_OPTIONS="suppressions=$LSAN_SUPPRESSIONS_FILE_PATH"
    - TESTER_EXIT_CODE=0
    - ./work/bin/flexisip_conference_tester --disable-stdout --verbose --parallel --parallel-max 1 --log-file $LOG_FILE_PATTERN || TESTER_EXIT_CODE=$?
    - echo $TESTER_EXIT_CODE
    - |
      if [ "$TESTER_EXIT_CODE" -ne 0 ]; then
        echo "Moving generated log files to ${LOGS_DIR}";
        sudo mkdir ${LOGS_DIR};
        sudo chmod 777 ${LOGS_DIR};
        mv ${LOG_FILE_PATTERN}_* ${LOGS_DIR};
        echo "Successfully moved files";
      fi
    - exit $TESTER_EXIT_CODE
  artifacts:
    when: always
    paths:
      - ${LOGS_DIR}/*
    reports:
      junit:
        - BCUnitAutomated-Results.xml
    expire_in: 1 week
